### ISSUE TITLE
Additional Measurement Tracking

### ISSUE THREAD

**Issue by Ocamond** [ronnnnnnnnnnnnn/etekcity_fitness_scale_ble#1]
Hi Ron,

First, thank you for creating this great add-on! It’s really useful and works very well.

As far as I understand, the add-on currently tracks only weight. Would it be possible to add support for tracking other measurements (e.g., body fat, etc.)?

Thank you in advance for considering this request, and I look forward to your response!

Best regards,
Ocamond

**Comment by ronnnnnnnnnnnnn** [comment]
Hi Ocamond,

Thanks for the feedback! I'm glad you've found it useful. Since you're the first to try it out, and I've only tested things on my own setup, I'm curious about your setup:
Which model do you have? ESF-551 or a different one?
Are you using Home Assistant OS or core/supervised/container? Running on Mac/Linux/Windows?

About tracking other measurements - sure, could be fun to try. The underlying library I created already reads the impedance measurement from the scale, which is likely the basis for those other metrics. The main thing will be calculating the body composition metrics from it.

From a quick look online there doesn't seem to be a definitive formula, as it depends on how the impedance is measured. The best approach might be to emulate the VeSync app's calculations. Maybe I can try decompiling the apk to look for their method. Or collecting lots of measurements and trying regression.

I'll do some more reading and give it some thought over the weekend and then I'll give it a try. I'll update how things go.

Best regards,
Ron

**Comment by Ocamond** [comment]
Here is the corrected English version:

Hi Ron,

Sorry for the late reply; it was a hectic week.

I’m using the ESF-551 with Home Assistant OS running on a Raspberry Pi. You really don’t need to invest the time if you’re short on it.

I also have the Xiaomi Mi Smart Scale 2, which works perfectly with Home Assistant.

Best regards,
Ocamond

**Comment by ronnnnnnnnnnnnn** [comment]
Done!

New release with support for body metrics is now available :-)
