### ISSUE TITLE
Installed but not updating sensors

### ISSUE THREAD

**Issue by chrisjwhite30** [ronnnnnnnnnnnnn/etekcity_fitness_scale_ble#4]
Having an issue with this integration, can you help, should I uninstall and reinstall it?
**Using Home Assistant Blue, latest updates
Core: 2024.11.3
Supervisor: 2024.11.4
Operating System: 13.2
Frontend: 20241106.2**
**Same scale ESF-551**
HA sees and installs the scale but nothing is updating when I get on the scale.
Some logs with errors are below.
_Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:365
integration: Sensor (documentation, issues)
First occurred: 7:13:01 AM (3 occurrences)
Last logged: 7:23:36 AM

Error while setting up etekcity_fitness_scale_ble platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/etekcity_fitness_scale_ble/sensor.py", line 168, in async_setup_entry
    await coordinator.async_start()
  File "/config/custom_components/etekcity_fitness_scale_ble/coordinator.py", line 89, in async_start
    await self._async_start()
  File "/config/custom_components/etekcity_fitness_scale_ble/coordinator.py", line 75, in _async_start
    await self._client.async_start()
  File "/usr/local/lib/python3.12/site-packages/etekcity_esf551_ble/parser.py", line 118, in async_start
    await self._scanner.start()
  File "/usr/local/lib/python3.12/site-packages/etekcity_esf551_ble/bluetooth.py", line 81, in start
    await self._backend.start()
  File "/usr/local/lib/python3.12/site-packages/bleak/backends/bluezdbus/scanner.py", line 185, in start
    self._stop = await manager.active_scan(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bleak/backends/bluezdbus/manager.py", line 423, in active_scan
    assert_reply(reply)
  File "/usr/local/lib/python3.12/site-packages/bleak/backends/bluezdbus/utils.py", line 20, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress_

**Comment by ronnnnnnnnnnnnn** [comment]
Hi @chrisjwhite30,

The issue seems to be [this one I mentioned in the readme](https://github.com/ronnnnnnnnnnnnn/etekcity_fitness_scale_ble?tab=readme-ov-file#raspberry-pi-4-and-other-linux-machines-using-bluez).

Can you try the solution suggested there for resetting the BT adapter and let me know if that resolves the issue for you?
For more details you can check out [this HA github thread](https://github.com/home-assistant/core/issues/76186#issuecomment-1204954485). It might require several attempts of resetting and restarting scanning and the BT adapter, but I think it should do the trick.

Let me know how it goes and whether the issue is resolved or not.

**Comment by chrisjwhite30** [comment]
I got it working. I tried the resetting bluetooth, but that didn't work. I ended up uninstalling completely, then re-installing and placed my feet on the scale during initial setup of the integration and saw the numbers changing in real time. Then after I completed the setup and stood on the scale, all the numbers were updated.
BTW, what kind of cards do you recommend on the dashboard? Will a graph show weight, etc over time?

**Comment by ronnnnnnnnnnnnn** [comment]
Great! Glad to hear it's working now. Just make sure the measurements update when you weigh yourself again, because if the Bluetooth issue still persists it can still be that the first measurement shows up but no subsequent measurements do due to Home Assistant not being able to reconnect to the scale. 

With regard to the card - I just use the entity card to show the current measurements. But yeah, if you want to see progression over time the history graph should work. Just be sure to change the number of hours to show from 24 to whatever you want (168 for a week for example).

Let me know if you encounter any other issues.

**Comment by chrisjwhite30** [comment]
Well, it didn't update this morning, so I guess it's not working after all.
I think I might try one of those esp32 bluetooth proxy things.

**Comment by ronnnnnnnnnnnnn** [comment]
I'd suggest trying again playing with the Bluetooth adapter: turning scanning off and on several times, and turning the adapter itself off and on several times, then restarting Home Assistant. 

If that doesn't solve it for you, you might want to consider connecting an external USB Bluetooth adapter as people in [the thread I've linked to](https://github.com/home-assistant/core/issues/76186#issuecomment-1204954485) seem to report that drives the issue, as it's related specifically to the internal adapter used by Raspberry Pi (and I guess Home Assistant Blue).

Also, be sure not to have another client fighting for the Bluetooth connection. For example, if you have the VeSync app open when stepping on the scale then the scale will connect to it and won't be able to connect to Home Assistant until it disconnects.
